### ISSUE TITLE
[FEATURE REQUEST] Always on?

### ISSUE THREAD

**Issue by csmarshall** [potrudeau/homebridge-messenger#8]
I *kinda* get the idea of having a master on off switch, but is there anyway to default it to *ON* instead off *off*? Or is this some weird homekit thing?  Right now I'm looking at setting up *another* plugin, to keep turning on the switch every minute, which seems cumbersome.

**Comment by raixer** [comment]
I only activated mine once. And it stays on even after reboots.

**Comment by potrudeau** [comment]
@csmarshall : Hi Charles! I'm not sure I understand! As @raixer mentioned, the plugin keeps the status of the main switch in cache, even after a reboot or restart. However, message switches are stateless: they are turned OFF after being turned ON, once the message is sent. This is by design and to prevent from sending 1 million messages per day.

**Comment by csmarshall** [comment]
Hmm, interesting, I guess I can flip the switch, maybe could we add the ability to have the switch defaulted to "on"?

**Comment by jsiegenthaler** [comment]
I just installed Messenger for use with IFTTT. Works well.
But why do you need a Messenger master switch? If I want to use Messenger, I want it on all the time. Can you add a config option to hide the Messenger master switch?

**Comment by potrudeau** [comment]
@jsiegenthaler : It allows more flexibility and the possibility to hide all messages under one single switch in the Homekit Home app.
